    <div class="banner">
        <div id="banner-roave-is">
            <h3>Roave is a hand-picked team of some of the most talented developers in the PHP community.</h3>
        </div>
    </div>

    <div class="content">

    <section id="home">
        <h1>Web development and PHP experts.</h1>

        <p>Roave is a full-service web development firm, offering services such as consulting, training, software development, and more.</p>

        <p>Roave employs some of the most recognized and accomplished experts in the industry to ensure that organizations have access to the talent they need, when they need it.</p>
    </section>

    <hr>

    <section id="labs">
        <h1>Labs &amp; Projects</h1>

        <article>
            <h3><a href="https://github.com/Roave/SecurityAdvisories">Roave Security Advisories</a></h3>

            <p>This package ensures that your application doesn't have installed dependencies with known security vulnerabilities.</p>
        </article>

        <article>
            <h3><a href="https://github.com/Roave/BetterReflection">Better Reflection</a></h3>

            <p>Better Reflection is a reflection API that aims to improve and provide more features than PHP's built-in reflection API.</p>
        </article>

        <article>
            <h3><a href="https://code-reviews.io/">Code-Reviews.io</a></h3>

            <p>COMING SOON — A SaaS solution from Roave which allows you to quickly and easily get expert code reviews and feedback on your project(s).</p>
        </article>

        <article>
            <h3>RoaveCast</h3>

            <p>COMING SOON — A SaaS for screen sharing, pair programming, and virtual conferences / training.</p>
        </article>

        <article>
            <h3>Unnamed AR Mapping Project</h3>

            <p>COMING SOON — A SaaS for creating augmented-reality games like Pokemon Go and Ingress.</p>
        </article>

    </section>




    </div>
