    <div class="banner">
        <div id="banner-roave-is">
            <h3>Roave is a hand-picked team of some of the most talented developers in the PHP community.</h3>
        </div>
    </div>

    <div class="content">

    <section id="home">
        <h1>Web development and PHP experts.</h1>

        <p>Roave is a full-service web development firm, offering services such as consulting, training, software development, and more.</p>

        <p>Roave employs some of the most recognized and accomplished experts in the industry to ensure that organizations have access to the talent they need, when they need it.</p>
    </section>

    </div>
