    <section id="labs">
        <h1>Labs</h1>

        <p>Welcome to Roave Labs. This is where we throw stuff against the wall to see what sticks.</p>

        <article>
            <h3><a href="https://github.com/Roave/SecurityAdvisories">Roave Security Advisories</a></h3>

            <p>This package ensures that your application doesn't have installed dependencies with known security vulnerabilities.</p>
        </article>

        <article>
            <h3><a href="https://github.com/Roave/BetterReflection">Better Reflection</a></h3>

            <p>Better Reflection is a reflection API that aims to improve and provide more features than PHP's built-in reflection API.</p>
        </article>

        <article>
            <h3><a href="https://code-reviews.io/">Code-Reviews.io</a></h3>

            <p>COMING SOON — A SaaS solution from Roave which allows you to quickly and easily get expert code reviews and feedback on your project(s).</p>
        </article>

        <article>
            <h3>RoaveCast</h3>

            <p>COMING SOON — A SaaS for screen sharing, pair programming, and virtual conferences / training.</p>
        </article>

        <article>
            <h3>Unnamed AR Mapping Project</h3>

            <p>COMING SOON — A SaaS for creating augmented-reality games like Pokemon Go and Ingress.</p>
        </article>

    </section>



