<?php $this->headTitle('Talks &amp; Events') ?>
    <section id="talks">
        <h1>Talks &amp; Events</h1>

        <div class="columns">
        <?php foreach($this->talks as $talk): ?>

        <article>
            <h3><?= $talk->title ?></h3>

            <p>By <?= $talk->presenter ?></p>

            <img src="https://joind.in/img/avg-rating-5.png">

            <?= $talk->abstract ?>

            <ul>
                <?php foreach($talk->events as $event): ?>
                <li><a href="https://joind.in/talk/<?= $event->joindin ?>"><?= $event->name ?></a></li>
                <?php endforeach ?>
            </ul>

        </article>

        <?php endforeach ?>
        </div>

    </section>
