<div class="content">
<section id="team">
    <h1>Our Team</h1>

    <?php foreach ($this->team as $roaver): ?>

    <article class="team-member">
        <img src="//www.gravatar.com/avatar/<?=$roaver->gravatar ?>?s=150&d=mm&r=g">
        <h3><?= $roaver->name ?></h3>
        <p><?= $roaver->bio ?></p>
    </article>

    <?php endforeach ?>

    <article class="team-member">
        <img src="//www.gravatar.com/avatar/879d7c8ea365a31443e6b890f68a7d7d?s=150&d=mm&r=g">
        <h3>Marco Pivetta (Ocramius)</h3>
        <p>Marco is a software developer by day, and a passionate open source software contributor, evangelist and supporter by night. He is part of the Doctrine team and an active Zend Framework 2 contributor. He is constantly looking for new challenges to deal with, especially when it comes to PHP.</p>
    </article>

    <article class="team-member">
        <img src="//www.gravatar.com/avatar/3a8d5011c49ac9a7702afd3853f5cc30?s=150&d=mm&r=g">
        <h3>James Titcumb (asgrim)</h3>
        <p>James has been a PHP developer for over 13 years, and has been programming since before that. He's a Zend Certified Engineer, and enjoys working with all things related to PHP. In his spare time he runs the PHP Hampshire user group and the PHP South Coast conference, contributes to various open source projects and occasionally speaks at conferences. He lives in Portsmouth in the UK with his wife and two children.</p>
    </article>

    <article class="team-member">
        <img src="//www.gravatar.com/avatar/c9e618a09b7a872be9376b099b688eda?s=150&d=mm&r=g">
        <h3>Ben Scholzen (DASPRiD)</h3>
        <p>Ben Scholzen is a Zend Certified Engineer who has been programming since his childhood, and started with PHP in 2000. In 2008 he started contributing to the Zend Framework, developing key components including Zend_Application. He joined the Zend Framework Community Review Team in 2010. For Zend Framework 2 he contributed features such as the new routing system and the internationalization layer.</p>
    </article>

</section>
</div>
