<?php $this->headTitle()->prepend('Our Clients'); ?>
<section class="team">
    <header>
        <h1>Meet some of our happy clients</h1>
    </header>
      <div class="featurette">
        <img class="featurette-image pull-center" src="images/zend.gif">
        <p class="lead">We have a great relationship with Zend. Evan is an instructor for Zend and teaches both their Zend Framework 2 Fundamentals and Advanced courses.</p>

        <div class="well">
            <h4 class="featurette-caption"><span class="muted">"I had the pleasure of working Evan while creating our new Zend Framework 2 Advanced course.  He helped to architect the course content and was a key contributor to the materials and class exercises.  Evan’s superior technical knowledge of Zend Framework 2 was paramount in allowing us to release this class with the high quality we strive for.  Evan is also a contract instructor for us, teaching the ZF2 Fundamentals and now Advanced course.  He has a great way of communicating and helping others to comprehend  difficult concepts.  Class feedback we’ve received on his teaching abilities & communication skills have been excellent.  I would definitely work with Evan again in either of these roles."</span></h4>
            <h4 class="featurette-caption">-Debbie Otterstetter, Global Training and Certification Manager</h4>
        </div>
      </div>

        <hr>

      <div class="featurette">
        <img class="featurette-image pull-center" src="images/coursio.png">
        <p class="lead">Evan works as a technical advisor for the Coursio development team. He assists the team by providing high-level architecture advice to create their e-learning platform.</p>

        <div class="well">
            <h4 class="featurette-caption"><span class="muted">"Working with Evan as an Advisor for Coursio was a keystone to success. Evan dug deep into our core framework, answering questions regading both code and architecture. We're looking forward to keep working together for a long time!"</span></h4>
            <h4 class="featurette-caption">-Henrick Hussfelt, CTO</h4>
        </div>
      </div>
</section>
