<section class="team">
    <header>
        <h1>Meet the Roave Team</h1>
    </header>

    <article class="member">
        <div class="photo">
            <?=$this->gravatar('evan@roave.com', ['img_size' => 180], ['alt' => 'Evan Coury']); ?>
            <div class="certs">
                <div class="zce5-3-logo"></div>
                <div class="zfce-logo"></div>
            </div>
        </div>
        <header>
            <hgroup>
                <h1>Evan Coury</h1>
                <h2>Owner</h2>
            </hgroup>
            <div class="links">
                <a href="https://github.com/EvanDotPro">github</a>
            </div>
        </header>
        <p>Evan is a Zend certified engineer for PHP 5.3 and Zend Framework, as well as a regular speaker at developer conferences around the world. He's worked on and led many large-scale web development projects to success. When not in front of a computer, Evan enjoys being outdoors with his two border collies and doing anything related to aviation.</p>
    </article>

    <article class="member">
        <div class="photo">
            <?=$this->gravatar('justin@roave.com', ['img_size' => 180], ['alt' => 'Justin Martin']); ?>
        </div>
        <header>
            <hgroup>
                <h1>Justin Martin</h1>
                <h2>Lead Developer</h2>
            </hgroup>
        </header>
        <p>Justin Martin is a PHP expert with over a decade of highly diverse PHP experience. He is recognized in the PHP community for being a <a href="http://www.php.net/manual/en/preface.php">significant contributor</a> to the official PHP manual as well as a founding member of the <a href="http://phpmentoring.org">PHP Mentoring</a> project. Justin is also our resident JavaScript and binary protocol expert. In his spare time, Justin enjoys riding motorcycles, bicycles, <a href="http://rvecafe.com/Assets5/bike01f.jpg">or anything with two wheels</a>.</p>
    </article>

     <article class="member">
        <div class="photo">
            <?=$this->gravatar('ben@roave.com', ['img_size' => 180], ['alt' => 'Ben Scholzen']); ?>
            <div class="certs">
                <div class="zce5-3-logo"></div>
                <div class="zce5-logo"></div>
                <div class="zfce-logo"></div>
            </div>
        </div>
        <header>
            <hgroup>
                <h1>Ben Scholzen</h1>
                <h2>Senior Developer</h2>
            </hgroup>
        </header>
        <p>Ben Scholzen is a Zend Certified Engineer who has been programming since his childhood, and started with PHP in 2000. In 2008 he started contributing to the Zend Framework, developing key components including Zend_Application. He joined the Zend Framework Community Review Team in 2010. For Zend Framework 2 he contributed features such as the new routing system and the internationalization layer.</p>
    </article>

     <article class="member">
        <div class="photo">
            <?=$this->gravatar('aleksey@roave.com', ['img_size' => 180], ['alt' => 'Aleksey Khudyakov']); ?>
            <div class="certs">
                <div class="zce5-3-logo"></div>
            </div>
        </div>
        <header>
            <hgroup>
                <h1>Aleksey Khudyakov</h1>
                <h2>Developer</h2>
            </hgroup>
        </header>
        <p></p>
    </article>

<hr /><hr />
    <article class="member">
        <h1>Evan Coury</h1>
        <h2>Owner</h2>
        <div class="photo">
            <img src="https://secure.gravatar.com/avatar/5fac6a9353bbc9235568e920cdd400f6?s=180"
                alt="Evan Coury" />
            <div class="certs">
                <div class="zce5-3-logo"></div>
                <div class="zfce-logo"></div>
            </div>
        </div>

        <p>Evan is a Zend certified engineer for PHP 5.3 and Zend Framework, as well as a regular speaker at developer conferences around the world. He's worked on and led many large-scale web development projects to success. When not in front of a computer, Evan enjoys being outdoors with his two border collies and doing anything related to aviation.</p>
    </article>
    <article class="member">
        <h1>Evan Coury</h1>
        <h2>Owner</h2>
        <div class="photo">
            <img src="https://secure.gravatar.com/avatar/5fac6a9353bbc9235568e920cdd400f6?s=180"
                alt="Evan Coury" />
        </div>

        <p>Evan is a Zend certified engineer for PHP 5.3 and Zend Framework, as well as a regular speaker at developer conferences around the world. He's worked on and led many large-scale web development projects to success. When not in front of a computer, Evan enjoys being outdoors with his two border collies and doing anything related to aviation.</p>
    </article>
    <article class="member">
        <h1>Evan Coury</h1>
        <h2>Owner</h2>
        <div class="photo">
            <img src="https://secure.gravatar.com/avatar/5fac6a9353bbc9235568e920cdd400f6?s=180"
                alt="Evan Coury" />
            <div class="certs">
                <div class="zce5-3-logo"></div>
                <div class="zce5-logo"></div>
                <div class="zfce-logo"></div>
                <div class="zce5-3-logo"></div>
                <div class="zce5-logo"></div>
                <div class="zfce-logo"></div>
            </div>
        </div>

        <p>Evan is a Zend certified engineer for PHP 5.3 and Zend Framework, as well as a regular speaker at developer conferences around the world. He's worked on and led many large-scale web development projects to success. When not in front of a computer, Evan enjoys being outdoors with his two border collies and doing anything related to aviation.</p>
    </article>
</section>
