<?php
//$this->headTitle()->prepend('Meet the Team');
$team = [
    [
        'name'  => 'Evan Coury (EvanDotPro)',
        'title' => 'Owner',
        'email' => 'evan@roave.com',
        'bio'   => 'Evan is a Zend certified engineer for PHP 5.3 and Zend Framework, as well as a regular speaker at developer conferences around the world. He\'s worked on and led many large-scale web development projects to success. When not in front of a computer, Evan enjoys being outdoors with his two border collies and doing anything related to aviation.',
        'certs' => ['zce5-3-logo', 'zfce-logo'],
        'zceid' => 'ZEND015223',
        'links' => [
            'github' => 'https://github.com/EvanDotPro',
        ],
    ],
    [
        'name'  => 'Justin Martin (FrozenFire)',
        'title' => 'Senior Developer',
        //'email' => 'justin@roave.com',
        'email' => 'evanatmtd+justin@gmail.com',
        'bio'   => 'Justin Martin is a PHP expert with over a decade of highly diverse PHP experience. He is recognized in the PHP community for being a <a href="http://www.php.net/manual/en/preface.php">significant contributor</a> to the official PHP manual as well as a founding member of the <a href="http://phpmentoring.org">PHP Mentoring</a> project. Justin is also our resident JavaScript and binary protocol expert. In his spare time, Justin enjoys riding motorcycles, bicycles, <a href="http://rvecafe.com/Assets5/bike01f.jpg">or anything with two wheels</a>.',
        'links' => [
            'github' => 'https://github.com/TheFrozenFire',
        ],
    ],
    [
        'name'  => 'Ben Scholzen (DASPRiD)',
        'title' => 'Senior Developer',
        'email' => 'ben@roave.com',
        'bio'   => 'Ben Scholzen is a Zend Certified Engineer who has been programming since his childhood, and started with PHP in 2000. In 2008 he started contributing to the Zend Framework, developing key components including Zend_Application. He joined the Zend Framework Community Review Team in 2010. For Zend Framework 2 he contributed features such as the new routing system and the internationalization layer.',
        'certs' => ['zce5-3-logo', 'zce5-logo', 'zfce-logo'],
        'zceid' => 'ZEND004767',
        'links' => [
            'github' => 'https://github.com/DASPRiD',
        ],
    ],
    [
        'name'  => 'Marco Pivetta (Ocramius)',
        'title' => 'Senior Developer',
        'email' => 'marco@roave.com',
        'bio'   => 'Marco aka Ocramius is a software developer by day, and a passionate open source software contributor, evangelist and supporter by night. He is part of the Doctrine team and an active Zend Framework 2 contributor, constantly looking for new challenges to deal with, especially when it comes to PHP.',
        //'zceid' => 'ZEND004767',
        'links' => [
            'github' => 'https://github.com/Ocramius',
        ],
    ],
    [
        'name'  => 'Rob Allen (Akrabat), Nineteen Feet',
        'title' => 'Partner / Consultant',
        'email' => 'rob@roave.com',
        'bio'   => 'Roave and <a href="http://19ft.com">Nineteen Feet</a> have partnered to form one of the strongest, most qualified PHP and Zend Framework consulting teams available. Rob Allen, of Nineteen Feet Limited, is a software developer and consultant with over 12 years experience in web development using PHP & technologies. He literally wrote the book on Zend Framework. Combining Rob and Evan’s extensive experience and extremely talented teams allows us to ensure we’re always offering the best possible solutions to our clients and take on projects of a much larger scale.',
        'certs' => ['zce5-logo', 'zfce-logo'],
        'zceid' => 'ZEND008272',
        'links' => [
            'github' => 'https://github.com/Akrabat',
        ],
    ],
    [
        'name'  => 'Nigel Lundsten (nlundsten)',
        'title' => 'Developer',
        //'email' => 'nigel@roave.com',
        'email' => 'nigel.lundsten@gmail.com',
        'bio'   => 'Nigel and Evan have been working together on various projects for well over 10 years. Nigel has extensive experience building complete web applications solving complex problems for a variety of industries.',
        'links' => [
            'github' => 'https://github.com/nclundsten',
        ],
    ],
    [
        'name'  => 'Aleksey Khudyakov (Xerkus)',
        'title' => 'Developer',
        'email' => 'aleksey@roave.com',
        'bio'   => 'Aleksy is a PHP 5.3 Zend Certified Engineer with nearly a decade of PHP experience. Among other things, he is recognized for his contributions to large open source projects such as Zend Framework 2 and SpeckCommerce. Aside from programming, Aleksy enjoys immersing himself in a good sci-fi novel.',
        'certs' => ['zce5-3-logo'],
        'zceid' => 'ZEND021085',
        'links' => [
            'github' => 'https://github.com/Xerkus',
        ],
    ],
    [
        'name'  => 'Priscilla Hubbard',
        'title' => 'Assistant to Evan Coury',
        'email' => 'evanatmtd+priscilla@gmail.com',
        'bio'   => 'Priscilla keeps everything running smoothly at Roave. She handles everything from client billing to payroll and travel arrangements. In her time off, Priscilla can typically be found spending quality time being tortured by her 2 boys.',
    ],
    [
        'name'  => 'Chloe',
        'title' => 'Border Collie',
        'email' => 'evanatmtd+chloe@gmail.com',
        'bio'   => 'Chloe has the very, very important role of making sure none of us at Roave work too hard. She has a keen sense of when you\'re trying very hard to focus on something and will choose that exact moment to drop her ball at your feet.',
    ],
];
?>
<section class="team">
    <header>
        <h1>Meet the Roave Team</h1>
    </header>

    <?php foreach($team as $member): ?>
    <article class="member">
        <div class="photo">
            <?=$this->gravatar($member['email'], ['img_size' => 180], ['alt' => $member['name']]); ?>
            <?php if (!empty($member['certs'])): ?>
            <div class="certs">
                <a href="http://www.zend.com/en/yellow-pages#show-ClientCandidateID=<?= $member['zceid']; ?>">
                <?php foreach($member['certs'] as $cert): ?>
                    <div class="<?=$cert; ?>"></div>
                <?php endforeach; ?>
                </a>
            </div>
            <?php endif; ?>
        </div>
        <header>
            <hgroup>
                <h1><?= $member['name']; ?></h1>
                <h2><?= $member['title']; ?></h2>
            </hgroup>
            <?php if (!empty($member['links'])): ?>
            <div class="links">
                <?php foreach($member['links'] as $link => $url): ?>
                    <a href="<?= $url; ?>"><?= $link;?></a>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>
        </header>
        <p><?= $member['bio']; ?></p>
    </article>
    <hr>
    <?php endforeach; ?>

</section>
