<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="/">
        <meta charset="utf-8">
        <title>Roave</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <link href="bootstrap/css/bootstrap.css" rel="stylesheet">
        <link rel="stylesheet" href="css/layout.css">
        <link rel="stylesheet" href="css/structure.css">
        <link rel="stylesheet" href="css/typography.css">
        <link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements --><!--[if lt IE 9]> <script src="bootstrap/js/html5shiv.js"></script> <![endif]-->
        <link href="images/favicon.png" rel="shortcut icon">
        <link href="images/favicon.ico" rel="shortcut icon">

        <link href="http://fonts.googleapis.com/css?family=Rambla" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" type="button">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li><a href="#about">About</a></li>
                            <li><a href="#contact">Contact</a></li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Dropdown
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
                        </ul>
                        <form class="navbar-form pull-right">
                            <input class="span2" placeholder="Email" type="text">
                            <input class="span2" placeholder="Password" type="password">
                            <button class="btn" type="submit">Sign in</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="main container">
            <div class="masthead">
                <div class="logo small"></div>
            </div>
            <hr>
            <?php echo $this->content; ?>
            <hr>
            <div class="footer">
                <p>&copy; Roave <?=date("Y")?></p>
            </div>
        </div>
        <script src="bootstrap/js/jquery.js"></script>
        <script src="bootstrap/js/bootstrap-transition.js"></script>
        <script src="bootstrap/js/bootstrap-alert.js"></script>
        <script src="bootstrap/js/bootstrap-modal.js"></script>
        <script src="bootstrap/js/bootstrap-dropdown.js"></script>
        <script src="bootstrap/js/bootstrap-scrollspy.js"></script>
        <script src="bootstrap/js/bootstrap-tab.js"></script>
        <script src="bootstrap/js/bootstrap-tooltip.js"></script>
        <script src="bootstrap/js/bootstrap-popover.js"></script>
        <script src="bootstrap/js/bootstrap-button.js"></script>
        <script src="bootstrap/js/bootstrap-collapse.js"></script>
        <script src="bootstrap/js/bootstrap-carousel.js"></script>
        <script src="bootstrap/js/bootstrap-typeahead.js"></script>
    </body>
</html>
