<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="/<?= $this->basePath(); ?>">
        <meta charset="utf-8">
        <title>Roave</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <link rel="stylesheet" href="css/style.css" >
        <link rel="stylesheet" href="css/layout.css">
        <link rel="stylesheet" href="css/structure.css">
        <link rel="stylesheet" href="css/typography.css">
        <link rel="stylesheet" href="css/bootstrap-responsive.css">
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]> <script src="js/html5shiv.js"></script> <![endif]-->
        <link href="images/favicon.png" rel="shortcut icon">
        <link href="images/favicon.ico" rel="shortcut icon">

        <link href="http://fonts.googleapis.com/css?family=Rambla" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div id="header-area">
            <div class="container">
                <div class="masthead">
                    <div class="logo small"></div>
                </div>
            </div>

            <div class="navbar navbar-inverse">
                <div class="navbar-inner">
                    <div class="container">
                        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div class="nav-collapse collapse">
                            <?php echo $this->navigation('navigation')->menu()->setPartial(array('application/topnav.phtml', 'default')); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="main container">
            <hr>
            <?php echo $this->content; ?>
            <hr>
            <div class="footer">
                <p>&copy; Roave 2012-<?=date('Y')?></p>
            </div>
        </div>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script src="js/bootstrap.js"></script>
    </body>
</html>
