<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="/<?= $this->basePath(); ?>">
        <meta charset="utf-8">
        <?php echo $this->headTitle('Roave')->setSeparator(' - '); ?>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <link rel="stylesheet" href="css/style.css" >
        <link rel="stylesheet" href="css/layout.css">
        <link rel="stylesheet" href="css/typography.css">
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]> <script src="js/html5shiv.js"></script> <![endif]-->
        <link href="images/favicon.png" rel="shortcut icon">
        <link href="images/favicon.ico" rel="shortcut icon">

        <link href="http://fonts.googleapis.com/css?family=Rambla" rel="stylesheet" type="text/css">
        <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
        <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    </head>
    <body>
        <div class="wrap">
            <header>
                <div class="container">
                    <div class="logo small"></div>
                </div>

                <div class="navbar navbar-inverse navbar-static-top">
                    <div class="navbar-inner">
                        <div class="container">
                            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <div class="nav-collapse collapse">
                                <?php echo $this->navigation('navigation')->menu()->setPartial(array('application/topnav.phtml', 'default')); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <div class="main container">
                <?php echo $this->content; ?>
            </div>
            <footer>
                <p class="copyright">&copy; Roave 2012-<?=date('Y')?></p>
            </footer>
            <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
            <script src="js/bootstrap.js"></script>
        </div>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
         
          ga('create', 'UA-42058149-1', 'roave.com');
          ga('send', 'pageview');
        </script>
    </body>
</html>
