<div class="carousel slide" id="myCarousel">
	<div class="carousel-inner">
		<div class="item active">
			<img alt="" src="../assets/img/examples/slide-01.jpg">
			<div class="container">
				<div class="carousel-caption">
					<h1>Example headline.</h1>
					<p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget
						quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor
						id nibh ultricies vehicula ut id elit.</p>
					<a class="btn btn-large btn-primary" href="#">Sign up today</a>
				</div>
			</div>
		</div>
		<div class="item">
			<img alt="" src="../assets/img/examples/slide-02.jpg">
			<div class="container">
				<div class="carousel-caption">
					<h1>Another example headline.</h1>
					<p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget
						quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor
						id nibh ultricies vehicula ut id elit.</p>
					<a class="btn btn-large btn-primary" href="#">Learn more</a>
				</div>
			</div>
		</div>
		<div class="item">
			<img alt="" src="../assets/img/examples/slide-03.jpg">
			<div class="container">
				<div class="carousel-caption">
					<h1>One more for good measure.</h1>
					<p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget
						quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor
						id nibh ultricies vehicula ut id elit.</p>
					<a class="btn btn-large btn-primary" href="#">Browse gallery</a>
				</div>
			</div>
		</div>
	</div>
	<a class="left carousel-control" data-slide="prev" href="#myCarousel">&lsaquo;</a>
	<a class="right carousel-control" data-slide="next" href="#myCarousel">&rsaquo;</a>
</div>
<hr>
<div class="row-fluid marketing">
	<div class="span6">
		<h4>Subheading</h4>
		<p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus
			mollis interdum.</p>
		<h4>Subheading</h4>
		<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras
			mattis consectetur purus sit amet fermentum.</p>
		<h4>Subheading</h4>
		<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
	</div>
	<div class="span6">
		<h4>Subheading</h4>
		<p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus
			mollis interdum.</p>
		<h4>Subheading</h4>
		<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras
			mattis consectetur purus sit amet fermentum.</p>
		<h4>Subheading</h4>
		<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
	</div>
</div>
