<div class="jumbotron">
    <h1>Web development and PHP experts.</h1>
    <p class="lead">Roave (rōv) is a full-service web development consulting firm specializing in PHP.</p>
    <a class="btn btn-large" href="<?= $this->url('about/team'); ?>">Meet the Team &raquo;</a>
</div>

<hr>
<div class="row-fluid marketing">
    <div class="span6">
        <h4>Development</h4>
        <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus
            mollis interdum.</p>
        <h4>Training</h4>
        <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras
            mattis consectetur purus sit amet fermentum.</p>
        <h4>Consulting</h4>
        <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
    </div>
    <div class="span6">
        <h4>Zend Framework</h4>
        <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus
            mollis interdum.</p>
        <h4>Scalability</h4>
        <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras
            mattis consectetur purus sit amet fermentum.</p>
        <h4>Best Practices</h4>
        <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
    </div>
</div>
