<div class="jumbotron">
    <h1>Web development and PHP experts.</h1>
    <p class="lead">Roave (rōv) is a full-service web development consulting firm specializing in PHP.</p>
    <a class="btn btn-large" href="<?= $this->url('about/team'); ?>">Meet the Team &raquo;</a>
</div>

<div class="client-logos">
    <img src="http://static.zend.com/img/logo.gif" />
    <img src="https://www.southwestmedical.com/images/SWM_Logo_Full.png" />
    <img src="http://coursio.com/images/coursio_logo.png" />
    <img src="https://www.callfire.com/sites/all/themes/callfire/images/logo.png" />
</div>
