<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<base href="/">
		<title>Roave</title>
		<meta content="width=device-width, initial-scale=1.0" name="viewport">
		<meta content="" name="description">
		<meta content="" name="author">
		<!-- Le styles -->
		<link href="bootstrap/css/bootstrap.css" rel="stylesheet">
		<link href="css/splash.css" rel="stylesheet">
		<style type="text/css">
			}
		</style>
		<link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
		<!-- HTML5 shim, for IE6-8 support of HTML5 elements --><!--[if lt IE 9]> <script src="bootstrap/js/html5shiv.js"></script> <![endif]-->
		<!-- Fav and touch icons -->
		<link href="../images/favicon.png" rel="shortcut icon">
	</head>
	<body>
		<div class="container-narrow">
			<div class="masthead">
				<img src="images/roave.png">
			</div>
			<hr>
			<div class="jumbotron">
				<h1>Coming Soon!</h1>
				<p class="lead">We are a company that specializes in software
					development, managing and training development teams, and we work with
					our clients' to customize and integrate their existing software in to
					live applications.</p>
			</div>
			<div class="row-fluid marketing text-center">
				<div class="span12">
					<a class="btn btn-large btn-warning" href="mailto:info@roave.com">Email
						Us!</a>
				</div>
			</div>
			<hr>
			<div class="footer">
				<p>&copy; MediaTech Designs, LLC 2013</p>
			</div>
		</div>
		<!-- /container -->
		<!-- Le javascript ================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="bootstrap/js/jquery.js"></script>
		<script src="bootstrap/js/bootstrap-transition.js"></script>
		<script src="bootstrap/js/bootstrap-alert.js"></script>
		<script src="bootstrap/js/bootstrap-modal.js"></script>
		<script src="bootstrap/js/bootstrap-dropdown.js"></script>
		<script src="bootstrap/js/bootstrap-scrollspy.js"></script>
		<script src="bootstrap/js/bootstrap-tab.js"></script>
		<script src="bootstrap/js/bootstrap-tooltip.js"></script>
		<script src="bootstrap/js/bootstrap-popover.js"></script>
		<script src="bootstrap/js/bootstrap-button.js"></script>
		<script src="bootstrap/js/bootstrap-collapse.js"></script>
		<script src="bootstrap/js/bootstrap-carousel.js"></script>
		<script src="bootstrap/js/bootstrap-typeahead.js"></script>
	</body>
</html>