<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Roave</title>
		<meta content="width=device-width, initial-scale=1.0" name="viewport">
		<link href="bootstrap/css/bootstrap.css" rel="stylesheet">
		<link rel="stylesheet" href="css/splash.css">
		<link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
		<!-- HTML5 shim, for IE6-8 support of HTML5 elements --><!--[if lt IE 9]> <script src="bootstrap/js/html5shiv.js"></script> <![endif]-->
		<link href="images/favicon.png" rel="shortcut icon">
		<link href="images/favicon.ico" rel="shortcut icon">
	</head>
	<body>
		
	</body>
</html>
